version: 2
updates:
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: github.com/sindresorhus/KeyboardShortcuts
        update-types:
          - version-update:semver-major
